#!/bin/bash

#ChonCloud Welcome
LINE='if [ -f /usr/bin/chonos-wsl-start ]; then /usr/bin/chonos-wsl-start; fi'
if ! grep -Fxq "$LINE" /root/.bashrc; then
  echo "$LINE" >> /root/.bashrc
fi

if ! grep -Fxq "$LINE" /home/*/.bashrc; then
  echo "$LINE" >> /home/*/.bashrc
fi

/usr/bin/chonosDDNSManager --conf -d WSLINSTALL -u "ddns_user" -t "ddns_token"
echo "root:root" | chpasswd

systemctl disable chonos-log.service
systemctl disable chonos-task.service
systemctl disable chonos-sysconfig.service 
systemctl disable chonos-ddnsAutoUpdater.service

/usr/bin/chonos-wsl-start
